Jjdzr11 js 6/15
infoshareacademy/JJDZR11-javaSmugglers pull request #3
Opened 2023-03-26 16:59 UTC by Blazej-Jendrzejewski

2023-03-26 17:33 UTC, tomlisow requested changes
Skompilowane klasy (katalog target) nie powinny trafiać na repozytorium.

2023-03-26 17:33 UTC, tomlisow commented on Zajecia/.gitignore
> +target/.gitignoere
cały katalog target powinien być ignorowany

2023-03-26 17:33 UTC, tomlisow commented on Zajecia/src/main/java/pl/isa/javasmugglers/App.java
> +        MenuGlowne menuGlowne = new MenuGlowne();
Trzymajcie się standardu nazewnictwa klas - a konkretnie wersji językowej.
Jak masz klasy np. User, DatabaseWriter itd, to wszystkie powinny być w tej samej konwencji.

2023-03-30 07:29 UTC, TomaszOdwald approved these changes

2023-03-30 07:29 UTC, TomaszOdwald commented on Zajecia/src/main/java/pl/isa/javasmugglers/DatabaseWriter.java
> +    public void addUserToDatabase(String userType, String userFirstName, String userLastName, String userEmail, String userPassword) {
Jeżeli ta metoda może się popsuć ze względu na jakiś wyjątek w środku, to fajnie by było, żeby zwracała informację czy jej się udało wykonać wszystko czy nie, ale to tak na przyszłość ;)

2023-03-30 07:29 UTC, TomaszOdwald commented on Zajecia/src/main/java/pl/isa/javasmugglers/MenuAddUser.java
> +    public int getValidInput() {
Macie już podobną metodę gdzie indziej, warto byłoby zrobić jakąś Utils'ową klasę, w której byłaby jedna taka funkcja do wczytywania intów, dla której podajecie zakres, który może być poprawny.

2023-04-01 19:58 UTC, tomlisow approved these changes

2023-04-14 08:12 UTC, merged